### ISSUE TITLE
Invalid character (_) in DID

### ISSUE THREAD

**Issue by kenhuang** [AraBlocks/did-uri#5]
Getting the following validation error on this did: `did:test:EiBMXFJVq2C05kweoYezVtU5HDbwoyTbQGf-xg_Q6HPKug`

```
SyntaxError: Invalid character (_) in "idstring
```

Following the [spec](https://w3c.github.io/did-core/#did-syntax) it did said
> idchar             = ALPHA / DIGIT / "." / "-" / "_"

**Comment by jwerle** [comment]
@kenhuang thanks for reporting this issue! We'll have a fix soon

**Comment by vipyne** [comment]
fixed with #6
